### ISSUE TITLE
how to display fractional star ratings.

### ISSUE THREAD

**Issue by laoniustudio** [MurhafSousli/ngx-bar-rating#21] opened 2018-06-12 23:37 UTC
Hi, how to display fractional star ratings. it's not working by give it decimal value.
thanks

**Comment by MurhafSousli** [comment] 2018-06-13 02:54
Hi, check this [stackblitz](https://stackblitz.com/edit/ngx-bar-rating-dj6gxr?file=app%2Fapp.component.html)
Duplicate of #17

**Closed by MurhafSousli** 2018-06-13 02:54 UTC
